### ISSUE TITLE
Vagrant/Docker file for ease of development

### ISSUE THREAD

**Issue by skrzepto** [fedora-infra/fmn.sse#27]
Create a docker file for latest fedora and epel7

**Comment by skrzepto** [comment]
checkout branch docker

https://github.com/fedora-infra/fmn.sse/tree/docker/docker

**Comment by skrzepto** [comment]
having a difficult time enabling rabbitmqserver in the docker image

**Comment by skrzepto** [comment]
Vagrant file is already merged into develop

**Comment by jeremycline** [comment]
I think we can close this since the Vagrant environment is merged.

**Comment by skrzepto** [comment]
@jeremycline I left it open for docker support since there was talk about dockerizing some of our infra but if docker img is not needed we can close.

Just a quick note, last time I tried to create the DockerFile I had issues setting up rabbitmq since systemd is stripped from the epel7 base image and the other solutions that go around systemd were a pain

**Comment by jeremycline** [comment]
Ah, okay. I don't really want to maintain two separate development environments unless it really needs to be done, and I imagine a production container would differ from a development one (maybe not? I've never containerized either one). How does closing this and if there's a need for a specific sort of container opening a new ticket sound?
