### ISSUE TITLE
Local tests show different results from vps benchmark

### ISSUE THREAD

**Issue by skrzepto** [fedora-infra/fmn.sse#29]
Over 1,000 connections I get Too many files open from pika. I'm wondering if the old objects are not getting garbage collected out.

**Comment by skrzepto** [comment]
This could be just my local instance since I'm hosting and benchmarking on the same machine

```
CRITICAL:pika.adapters.base_connection:Could not get addresses to use: [Errno 24] Too many open files (localhost)
```

**Comment by pypingou** [comment]
Oh, that rings a painful bell :(

**Comment by skrzepto** [comment]
Looks like ulimit might be the issue here.

after following this article http://www.tecmint.com/increase-set-open-file-limits-in-linux/

I'm able to comftorably go up to 13111117 (what my 2nd vps and my personal machine can give out before the network is cut on them).

**Comment by skrzepto** [comment]
even though before it was saying 

```
(sse)[root@centos-512mb-nyc1-01 fmn.sse]# ulimit
unlimited
```
the limit was 1024 though

after following article I was able to get it to 8096
```
(sse)[root@centos-512mb-nyc1-01 fmn.sse]# ulimit -n
8192
```

**Comment by skrzepto** [comment]
Okay I am able to push 8,000 connections but the real bench marks is that its hovering around 80% cpu usage at that load. Still decent but nothing like the false positive I thought was before (100k at 35%  usage i wish!)
