### ISSUE TITLE
Some Limitations

### ISSUE THREAD

**Issue by skrzepto** [fedora-infra/fmn.sse#33]
* Once the program hits its ulimit it crashes. Should we reject new incoming streams once it hits lets say 90% cap from the ulimit and leave the rest for handling 503 errors? This allows the program to still run but won't allow it to crash.

* Program Linearly passes through each connections to send out messages. But each request is independent of each other. This could be a good spot for multi threading optimization.

**Comment by skrzepto** [comment]
Here's a profile log after running `python -m cProfile -o prof fmn/sse/sse_webserver.py`
with a stress test command `./wrk -t4 -c 800 -d300s http://localhost:8080/user/skrzepto`

[stats.txt](https://github.com/fedora-infra/fmn.sse/files/415357/stats.txt)

Some things that jump out at me is that logging takes a big chunk of the time. 

Feedque __init__ took about 3.5 seconds if I stored this instead of throwing it away each time I could save that time. Then I'll need to figure out how to share the same object with mutex locking or rethink that file. 

push_sse takes about .05ms for each message to send which is okay.
-----

Comparing write_messages_all_connections total time (54.196s)
push_sse total time (11.235s) 
get_payload(4.463s)
FeedQueue ( init 3.292 +  get channel 3.290 +  get one message 1.162   = 7.744s)

and there was enough messages in the queue so its not waiting for messages.

If my math is correct this means it took about 30s it takes to iterate over an array of 800 connections

**Comment by skrzepto** [comment]
[stats2.txt](https://github.com/fedora-infra/fmn.sse/files/415473/stats2.txt)

It seems after running on the branch `fix-log-spam`

I was able to drop the time in write all messages ~66%

```
     5    ncalls  tottime  percall  cumtime  percall filename:lineno(function)                      |     5    ncalls  tottime  percall  cumtime  percall filename:lineno(function)

    14       301    0.295    0.001   18.565    0.062 subscriber.py:38(write_messages_all_connection>|    14       302    0.575    0.002   54.196    0.179 subscriber.py:38(write_messages_all_connections)         

```

**Comment by skrzepto** [comment]
Tried out the theory of storing the feedqueue object and it's looking good. Slashed the time spent in FeedQueue. 

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      302    0.004    0.000    0.975    0.003 subscriber.py:75(get_payload)
      302    0.003    0.000    0.961    0.003 FeedQueue.py:23(receive_one_message)
        1    0.000    0.000    0.009    0.009 FeedQueue.py:5(__init__)
        1    0.000    0.000    0.009    0.009 FeedQueue.py:59(_get_pika_channel_connection)
    ....
    ....
   240376    1.664    0.000   10.876    0.000 subscriber.py:27(push_sse)
      302    0.277    0.001   12.297    0.041 subscriber.py:42(write_messages_all_connections)

```

**Comment by skrzepto** [comment]
Next optimization is to split up the connections array for multi threading since each connection is independent of each other.

**Comment by skrzepto** [comment]
http://stackoverflow.com/questions/2846653/how-to-use-threading-in-python/28463266#28463266


this is exactly what I want to do. Create a map and run a function on each request

**Comment by skrzepto** [comment]
branch `map-work` has some of the prototypes to write the messages faster. Current issue is that it doesn't close the connections correctly

**Comment by atelic** [comment]
What if you did something like:

```python
with Pool(8) as pool:
    pool.map(func, connections)
    self.logger.info("Total Connections: " + str(len(connections)))
```

**Comment by atelic** [comment]
nevermind, that's only available in python 3.3+

**Comment by skrzepto** [comment]
@atelic 
The problem I am running into now is that its erroring that it can't pickle some objects. Even though it worked 30 min ago with pathos multithreading.

**Comment by skrzepto** [comment]
also beware the process are broken and create zombies. you will need to sigkill the processes

**Comment by skrzepto** [comment]
So it looks like the multiprocess lib acts like fork which tries to pickle the entire file. When I removed the feedqueue object (uses pika) then it wouldn't error about pickling it.

Possible solution is to create a new file that just stores the connections and has sse_push function.

Now new problem is that

```
e/subscriber.py", line 63, in write_messages_all_connections
    pp.map(func, connections)
  File "/home/skrzepto/.virtualenvs/sse/lib/python2.7/site-packages/pathos/multiprocessing.py", line 136, in map
    return _pool.map(star(f), zip(*args)) # chunksize
  File "/home/skrzepto/.virtualenvs/sse/lib/python2.7/site-packages/multiprocess/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/skrzepto/.virtualenvs/sse/lib/python2.7/site-packages/multiprocess/pool.py", line 567, in get
    raise self._value
exceptions.ValueError: file descriptor cannot be a negative integer (-1)

```

**Comment by skrzepto** [comment]
After playing around with this for awhile it seems that twisted requests can't be pickled or dill.
Perhaps doing the old fashion thread might work.

There are some nicer networking frameworkds as aiohttp or uvloop but they are all py3+ only but we need py2 support to release this in epel7

**Comment by skrzepto** [comment]
Closing issue since new code uses defer for writing to stream
