### ISSUE TITLE
Investigate the Pika Twisted connection adapter

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn.sse#48]
I noticed the current connection adapter used is the [BlockingConnection](https://github.com/fedora-infra/fmn.sse/blob/2c23f05aa685b84e29195db4986876e2f08fb723/fmn/sse/FeedQueue.py#L59). This ticket is mostly just a note to myself to investigate the Pika-provided [TwistedConnection](https://pika.readthedocs.io/en/0.10.0/modules/adapters/twisted.html) adapter.

I suspect it will be much easier to work with and offer better performance within Twisted. If this has already been investigated please let me know :smile:.

**Comment by skrzepto** [comment]
This would be nice if TwistedConnection allowed to consume messages instead of the current polling each second. Pika has consume but like mentioned it blocks the thread.

**Comment by jeremycline** [comment]
Okay, so here are my findings. I also want to outline my understanding of what the current situation in, mostly because Twisted is tricky and easy to misunderstand and hopefully someone can point out any misunderstandings I have.

# The Current Situation

Currently, a `twisted.internet.task.LoopingCall` is created for each `key` (which looks to be `(exchange, queue)`). This looping call connects to RabbitMQ through a `pika.BlockingConnection`. Once every second, the `fmn.sse.subscriber.SSESubscriber.write_messages_all_connections` is called. This results in a [basic_get](https://pika.readthedocs.io/en/0.10.0/modules/adapters/blocking.html#pika.adapters.blocking_connection.BlockingChannel.basic_get) call to RabbitMQ which may return with a message or nothing if the queue is empty.

This is, based on my understanding of Twisted (and let me reiterate that I'm not an expert), a problem. There is a great deal of expensive, blocking network I/O that's occurring inside Twisted's reactor loop (which means we aren't taking advantage of Twisted at all):
- Establishing the initial connection with the RabbitMQ server
- Polling the server 1 time per second per queue. If there are 1000 users, there are 1000 blocking `basic_get` calls to RabbitMQ.

# Our Options

pika provides two Twisted-aware connection classes: [TwistedConnection](https://pika.readthedocs.io/en/0.10.0/modules/adapters/twisted.html#pika.adapters.twisted_connection.TwistedConnection) and [TwistedProtocolConnection](https://pika.readthedocs.io/en/0.10.0/modules/adapters/twisted.html#pika.adapters.twisted_connection.TwistedConnection).

## TwistedConnection

`TwistedConnection` uses the blocking `socket` module to connect to RabbitMQ, but it does implement the `IReadWriteDescriptor` interface for Twisted so after the blocking initial connection, I/O to the socket takes advantage of the Twisted reactor.

## TwistedProtocolConnection

`TwistedProtocolConnection` uses the Twisted functions for establishing both TCP and TLS connections so they are non-blocking and take advantage of the Twisted reactor. The downside to Twisted handling the connection is that the API differs from the standard `pika` connection API in several ways: you cannot register a callback for `on_connection` and, because Twisted is handling the connection, the host, port and ssl values of the connection parameters are ignored.

I think we should go with the `TwistedProtocolConnection`, although I'm open to other opinions!
