### ISSUE TITLE
Change pika to consume instead of receiving one message at a time

### ISSUE THREAD

**Issue by skrzepto** [fedora-infra/fmn.sse#5]
For now i have every 1 second poll the queue and send updates but it would be nice to use pika consume and set a callback to send the notifications to all active connections

**Comment by skrzepto** [comment]
why this was done at first was that twisted would error out saying too much data. I'm wondering if we can consume and wait 1 second before sending out the data if that would work better.

**Comment by pypingou** [comment]
you can tell pika to consume 1 message at a time check for ``prefetch_count``

**Comment by skrzepto** [comment]
I came across an article that pika server will close the blocking pika connection after a certain amount of time has passed. One of the solutions was to create a heart beat to the server. This may get more complex then necessary when comparing polling one message a second.

**Comment by pypingou** [comment]
A solution for this is: https://github.com/fedora-infra/fmn.consumer/commit/367341c817f1e3598f908a6166aae443ab3c3e12

**Comment by skrzepto** [comment]
Notes:
1.
when using the call back, the first arguments must match exactly what basic_consume expects and then we can add the additonal parameters

2. 
Basic_consume is a blocking call and polls just the same as I do each second, so not sure if its worth converting

**Comment by skrzepto** [comment]
Fixed in #52
