### ISSUE TITLE
What is the license for fmn.sse?

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/fmn.sse#66]
The LICENSE in the repository root indicates GPLv3, but the setup.py simply says "GPL" without a version and the license I added to fmn/sse/server.py is GPLv2+.

My preference is GPLv2+, but I believe all the contributors need to agree.

@skrzepto @pypingou

**Comment by skrzepto** [comment]
+1 on GPLv2+

I believe when I created the repo I accidentally clicked on GPLv3. But from what I recall majority of our repos have GPLv2+ license so lets stick with that

**Comment by jeremycline** [comment]
@atelic I see you also have a commit on here, are you also okay with GPLv2+?

**Comment by pypingou** [comment]
👍 for me :)

**Comment by atelic** [comment]
+1 sounds good to me! :)

**Comment by jeremycline** [comment]
Great, thanks everyone!
